# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/unicornt/mycsmith

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/unicornt/mycsmith

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unicornt/mycsmith/CMakeFiles /home/unicornt/mycsmith/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unicornt/mycsmith/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TryFunc

# Build rule for target.
TryFunc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TryFunc
.PHONY : TryFunc

# fast build rule for target.
TryFunc/fast:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/build
.PHONY : TryFunc/fast

Random.o: Random.cpp.o

.PHONY : Random.o

# target to build an object file
Random.cpp.o:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/Random.cpp.o
.PHONY : Random.cpp.o

Random.i: Random.cpp.i

.PHONY : Random.i

# target to preprocess a source file
Random.cpp.i:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/Random.cpp.i
.PHONY : Random.cpp.i

Random.s: Random.cpp.s

.PHONY : Random.s

# target to generate assembly for a file
Random.cpp.s:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/Random.cpp.s
.PHONY : Random.cpp.s

StructGenerator.o: StructGenerator.cpp.o

.PHONY : StructGenerator.o

# target to build an object file
StructGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/StructGenerator.cpp.o
.PHONY : StructGenerator.cpp.o

StructGenerator.i: StructGenerator.cpp.i

.PHONY : StructGenerator.i

# target to preprocess a source file
StructGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/StructGenerator.cpp.i
.PHONY : StructGenerator.cpp.i

StructGenerator.s: StructGenerator.cpp.s

.PHONY : StructGenerator.s

# target to generate assembly for a file
StructGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/StructGenerator.cpp.s
.PHONY : StructGenerator.cpp.s

TryFunc.o: TryFunc.cpp.o

.PHONY : TryFunc.o

# target to build an object file
TryFunc.cpp.o:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/TryFunc.cpp.o
.PHONY : TryFunc.cpp.o

TryFunc.i: TryFunc.cpp.i

.PHONY : TryFunc.i

# target to preprocess a source file
TryFunc.cpp.i:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/TryFunc.cpp.i
.PHONY : TryFunc.cpp.i

TryFunc.s: TryFunc.cpp.s

.PHONY : TryFunc.s

# target to generate assembly for a file
TryFunc.cpp.s:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/TryFunc.cpp.s
.PHONY : TryFunc.cpp.s

common/common.o: common/common.cpp.o

.PHONY : common/common.o

# target to build an object file
common/common.cpp.o:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/common/common.cpp.o
.PHONY : common/common.cpp.o

common/common.i: common/common.cpp.i

.PHONY : common/common.i

# target to preprocess a source file
common/common.cpp.i:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/common/common.cpp.i
.PHONY : common/common.cpp.i

common/common.s: common/common.cpp.s

.PHONY : common/common.s

# target to generate assembly for a file
common/common.cpp.s:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/common/common.cpp.s
.PHONY : common/common.cpp.s

common/type.o: common/type.cpp.o

.PHONY : common/type.o

# target to build an object file
common/type.cpp.o:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/common/type.cpp.o
.PHONY : common/type.cpp.o

common/type.i: common/type.cpp.i

.PHONY : common/type.i

# target to preprocess a source file
common/type.cpp.i:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/common/type.cpp.i
.PHONY : common/type.cpp.i

common/type.s: common/type.cpp.s

.PHONY : common/type.s

# target to generate assembly for a file
common/type.cpp.s:
	$(MAKE) -f CMakeFiles/TryFunc.dir/build.make CMakeFiles/TryFunc.dir/common/type.cpp.s
.PHONY : common/type.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TryFunc"
	@echo "... Random.o"
	@echo "... Random.i"
	@echo "... Random.s"
	@echo "... StructGenerator.o"
	@echo "... StructGenerator.i"
	@echo "... StructGenerator.s"
	@echo "... TryFunc.o"
	@echo "... TryFunc.i"
	@echo "... TryFunc.s"
	@echo "... common/common.o"
	@echo "... common/common.i"
	@echo "... common/common.s"
	@echo "... common/type.o"
	@echo "... common/type.i"
	@echo "... common/type.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

